version: "3.9"

services:
  generator:
    build:
      context: .
      dockerfile: ./docker/generator.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    container_name: generate_container

networks:
   default:
     name: "connect-service"
     external: true